apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dep
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: myapp
          image: IMAGE
          env:
            - name: ENV
              value: "staging"