resources:
- ./../../base
patches:
- path: deployment.yaml

namespace: myapp-prod

images:
- name: IMAGE
  newName: mluukkai/pock
  newTag: "1"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
